<!--html head部分  通过引入文件完成(分别适应于PC和手机)-->
<?php include($plume['ROOT_PATH'] . "modules/Example/View/layout/layoutP.phtml"); ?>
<?php
$users = null;
if (isset($data['users'])) {
    $users = $data['users'];
}
if ($plume['error']) {
    echo $data;
}
?>
<div class="container">
<div class="row">
<div class="col-md-12">
<div class="panel panel-default">
        <div class="panel-heading text-center">Plume Example</div>
        <table class="table table-striped table-bordered table-hover table-condensed">
            <tr>
                <th class="text-center">名字</th>
                <th class="text-center">密码</th>
                <th class="text-center">电话</th>
                <th class="text-center">操作</th>
            </tr>
                <?php
                if (empty($users)) {
                    ?>
                    <tr>
                    <td colspan="4">没有找到注册会员</td>
                    </tr>
                    <?php
                } else {
                    foreach ($users as $value) {
                        ?>
                        <tr>
                        <td class="text-center">
                            <?php $view->write($value['username']) ?>
                        </td>
                        <td class="text-center">
                            <?php
                            echo $value['password'];
                            ?>
                        </td>
                        <td class="text-center">
                            <?php
                            echo $value['tel'];
                            ?>
                        </td>
                        <td class="text-center">
                            <a href="/example/index/edit">新增 | </a>
                            <a href="/example/index/edit?id=<?php echo $value['id'];?>">修改 | </a>
                            <a name="delete" userid="<?php echo $value['id'];?>">删除</a>
                        </td>
                        </tr>
                        <?php
                    }
                }
                ?>
        </table>
    </div>
    <div class="panel-heading text-center">
        <nav>
            <ul class="pagination">
                <li class="disabled"><a href="#">&laquo;</a></li>
                <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&raquo;</a></li>
            </ul>
        </nav>
    </div>
</div><!--end panel-->
</div><!--end col-->
</div><!--end row-->
</div><!--end container-->
<!--html body部分 结束-->

<!--html foot部分  通过引入文件完成-->
<?php include($plume['ROOT_PATH'] . "modules/Example/View/layout/footer.phtml"); ?>
<script src="/js/userinfo.js"></script>